version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: mtg_cards
    restart: unless-stopped
    ports:
      - 8080:80
    links:
      - django
  django:
    build:
      context: .
      dockerfile: Dockerfile
      target: django
    restart: unless-stopped
    ports:
      - 8000:8000
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27018:27017
    secrets:
      - mongo_root_password
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_root_password
      - MONGO_INITDB_DATABASE=cards
    volumes:
      - mongo:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

secrets:
  mongo_root_password:
    file: ./secrets/mongo_root_password
volumes:
  mongo: